version: '3.3'

services:
  db:
    image: mysql:8.0.17
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: lackky
      MYSQL_DATABASE: lackky
      MYSQL_USER: lackky
      MYSQL_PASSWORD: lackky
  php:
    depends_on:
      - db
      - redis
    image: gsviec/nginx-php:7.4
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    environment:
      PHP_DISPLAY_ERRORS: 'On'
  phpmyadmin:
    restart: 'no'
    image: phpmyadmin/phpmyadmin:4.6
    depends_on:
      - db
    ports:
      - "9090:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: lackky
  redis:
    image: redis:alpine
  nginx:
    depends_on:
      - php
    image: nginx:1.19
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
#  elasticsearch:
#    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.0'
#    volumes:
#      - 'esdata:/usr/share/elasticsearch/data'
#    environment:
#      - cluster.name=docker-cluster
#      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
#      - discovery.type=single-node
#    ports:
#      - 9200:9200
#      - 9300:9300
#  kibana:
#    image: 'docker.elastic.co/kibana/kibana:7.6.0'
#    depends_on:
#      - elasticsearch
#    environment:
#      SERVER_NAME: localhost
#      ELASTICSEARCH_URL: 'http://elasticsearch:9200/'
#    ports:
#      - 5601:5601
volumes:
  db_data:
